development:
  clients:
    default:
      database: polldozer
      hosts:
        - localhost:27017

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>

test:
  clients:
    default:
      database: polldozer_test
      hosts:
        - localhost:27017
