development:
  sessions:
    default:
      database: polldozer
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>

test:
  sessions:
    default:
      database: polldozer_test
      hosts:
        - localhost:27017
